name: Release
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install and build (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          cargo build --release

      - name: Install and build (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          cargo build --release
        
      - name: Install and build (macos)
        if: matrix.platform == 'macos-latest'
        run: |
          cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-artifact
          path: target/${{ matrix.platform }}/release/
